import type { Metadata } from "next";
import { Inter, Bangers,  Roboto_Condensed } from "next/font/google";
import "../globals.css";
import Image from '../../../public/images/Logo.svg'

const inter = Inter({ subsets: ["latin"] });
const bangers = Bangers({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-bangers',
    display: 'swap',
});
const robotoCondensed = Roboto_Condensed({
    subsets: ['latin'],
    weight: ['400', '500'],
    variable: '--font-roboto-condensed',
    display: 'swap',
});

export const metadata: Metadata = {
    title: "KAI",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.className} ${bangers.className} `}>
        {children}
        </body>
        </html>
    );
}
